/* Configuration for ada_c_demo generated by Alire */
#ifndef ADA_C_DEMO_CONFIG_H
#define ADA_C_DEMO_CONFIG_H

#define CRATE_VERSION "0.1.0-dev"
#define CRATE_NAME "ada_c_demo"

#define ALIRE_HOST_OS "windows"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "msys2"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
