name = "lal_adapter"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Charles Reynolds"]
maintainers = ["Charles Reynolds <charlesareynolds@gmail.com>"]
maintainers-logins = ["charlesareynolds"]
[[depends-on]]
libadalang = "^22.0.0"
[[depends-on]]
gnatcoll = "^22.0.0"
